import { execFileSync } from "child_process";
import { readFileSync } from "fs";
import { join } from "path";

const root = join(__dirname, "..");
export const GENERATED_PATH = join(root, "src/generated/tenant-init-sql.ts");

/** The full SQL that creates a business database: the Prisma schema from empty, plus tenant-extras.sql. */
export function buildTenantSql(): string {
  const schema = execFileSync(
    join(root, "node_modules/.bin/prisma"),
    ["migrate", "diff", "--from-empty", "--to-schema-datamodel", join(root, "prisma/schema.prisma"), "--script"],
    { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] },
  );
  const extras = readFileSync(join(root, "prisma/tenant-extras.sql"), "utf8");
  return `${schema.trim()}\n\n${extras.trim()}\n`;
}

/** The generated module: a string constant, so it's bundled with the compiled code (no runtime file reads). */
export function renderModule(sql: string): string {
  return [
    "// Generated by `npm run tenant:sql` from prisma/schema.prisma and prisma/tenant-extras.sql. Do not edit.",
    `export const TENANT_INIT_SQL = ${JSON.stringify(sql)};`,
    "",
  ].join("\n");
}
